Name:           ros-indigo-pyros-common
Version:        0.4.1
Release:        1%{?dist}
Summary:        ROS pyros_common package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-pyros-config >= 0.1.5
Requires:       ros-indigo-pyzmp >= 0.0.14
BuildRequires:  ros-indigo-catkin >= 0.6.18
BuildRequires:  ros-indigo-catkin-pip >= 0.2.0
BuildRequires:  ros-indigo-pyros-config >= 0.1.5
BuildRequires:  ros-indigo-pyzmp >= 0.0.14

%description
Common subpackages for Pyros framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Apr 19 2017 AlexV <asmodehn@gmail.com> - 0.4.1-1
- Autogenerated by Bloom

* Wed Apr 19 2017 AlexV <asmodehn@gmail.com> - 0.4.1-0
- Autogenerated by Bloom

* Mon Mar 27 2017 AlexV <asmodehn@gmail.com> - 0.4.0-3
- Autogenerated by Bloom

* Sat Jan 21 2017 AlexV <asmodehn@gmail.com> - 0.4.0-2
- Autogenerated by Bloom

* Thu Jan 19 2017 AlexV <asmodehn@gmail.com> - 0.4.0-1
- Autogenerated by Bloom

* Wed Jan 18 2017 AlexV <asmodehn@gmail.com> - 0.4.0-0
- Autogenerated by Bloom

